### ISSUE TITLE
テーブル設計

### ISSUE THREAD

**Issue by campbel2525** [nabecamel/ec_demo#3]
# タスクのゴール
ecサイトにあたって必要なテーブルを設計する

**Comment by campbel2525** [comment]
users ユーザーテーブル
id: pk
email: メールアドレス, varchar(255), nn, uq
password: パスワード, varchar(255), nn
name: 名前, varchar(255), nn
post_code: 郵便番号, varchar(10), nn
address1: 住所1, varchar(255), nn
address2: 住所2, varchar(255), nn
tel: 電話番号, varchar(15), nn
created_at: 作成日時, datetime, nn
updated_at: 更新日時, datetime, nn

products 商品テーブル
id: pk
code: 商品コード, varchar(255), nn, uq
name: 商品名, varchar(255)
unit_price: 単価, unsignedinteger, nn
percent_tax: 税率, unsignedinteger, nn
created_at: 作成日時, datetime, nn
updated_at: 更新日時, datetime, nn

orders 注文テーブル
id: pk
user_id: ユーザーid, nn, fk
code: 注文コード, varchar(255), nn, uq
post_code: ユーザー郵便番号, varchar(10), nn
user_address1: ユーザー住所1, varchar(255), nn
user_address2: ユーザー住所2, varchar(255), nn
user_tel: ユーザー電話番号, varchar(15), nn
user_email: ユーザーemail, varchar(255), nn
user_name: ユーザー名, varchar(255), nn
shipping_post_code: 配送先ユーザー郵便番号, varchar(10), nn
shipping_user_address1: 配送先ユーザー住所1, varchar(255), nn
shipping_user_address2: 配送先ユーザー住所2, varchar(255), nn
shipping_user_tel: 配送先ユーザー電話番号, varchar(15), nn
shipping_user_email: 配送先ユーザーemail, varchar(255), nn
shipping_user_name: 配送先ユーザー名, varchar(255), nn
tax: 税金, unsignedinteger, nn
subtotal: 小計, unsignedinteger, nn
total_price: 合計金額, unsignedinteger, nn
payment_dated_at: 支払い日時, datetime
created_at: 作成日時, datetime, nn
updated_at: 更新日時, datetime, nn

order_details 注文詳細テーブル
id: pk
order_id: 注文id, nn, fk
product_id: 商品id, nn, fk
product_code: 商品コード, varchar(255), nn
product_name: 商品名, varchar(255), nn
product_unit_price: 単価, unsignedinteger, nn
product_percent_tax: 税率, unsignedinteger, nn
purchase_number 購入数, unsignedinteger, nn
price: 金額, unsignedinteger, nn
created_at: 作成日時, datetime, nn
updated_at: 更新日時, datetime, nn



## テーブルの使い方


このテーブルのイメージとしては添付画像の
- 赤でかっこってある部分はorders
- 黒でかっこってある部分はorder_details
になります

補足
ordersでユーザー情報を保存している理由は、ユーザーが住所などを変えても当時発送した場所を残しておくためです
order_detailsで商品情報を保存している理由は、商品の値段が変わったとしても当時の商品の値段を表示する必要があるためです。例えば購入履歴に表示する商品の値段は現在の値段ではなく、買った当時の値段を表示させる必要があるためです

<img width="424" alt="スクリーンショット 2024-03-20 2 34 13" src="https://github.com/nabecamel/ec_demo/assets/22098473/0c6a5c18-a80c-4df9-b60d-6b558703d344">

**Comment by campbel2525** [comment]
@nabecamel
nabecamelさんにも確認いただきOKならばコメントください！

もしわからない箇所や修正した方がいい箇所があればコメントおねがします

**Comment by nabecamel** [comment]
@campbel2525 
お疲れ様です！
設計していただいてありがとうございます！
基本的には理解しました！
 質問が二つあります！
・id に関しては、uqである必要はないのですか？それともpkがその意味も含んでいるのでしょうか？
・注文テーブルには、id（主キー）はいらないのでしょうか？

**Comment by campbel2525** [comment]
>id に関しては、uqである必要はないのですか？それともpkがその意味も含んでいるのでしょうか？

pkは主キーという意味なのでユニークを含みますね

pkは文字列でもいいのですが、ここではpkは
- ユニーク
- オートインクリメント
- nn
- 整数値
と言うふうにしてください。
この辺あまり意識していなかったのですが、たいていのフレームワークではこれが推奨されていそうですね。



>注文テーブルには、id（主キー）はいらないのでしょうか？

ありがとうございます。
必要ですね
追加しました！
