### ISSUE TITLE
マイグレーションファイルを作成する

### ISSUE THREAD

**Issue by campbel2525** [nabecamel/ec_demo#5]
# タスクのゴール

マイグレーションを作成する

注意点
mainに直接マージしないで、プルリクを作ること
レビューもしてもらうこと

**Comment by nabecamel** [comment]
@campbel2525 
マイグレーションファイルの作成方法があまりわかっていないのですが、
ディレクトリ（models)を作って、その中にテーブル定義みたいなものを書いていく感じでしょうか？

**Comment by campbel2525** [comment]
@nabecamel 

~~models/products.py~~
~~models/orders.py~~
~~を作ってその中に入れる感じですね！~~
~~products.pyにはproducts~~
~~orders.pyにはordersとorder_details~~
~~って感じですね！~~


具体的なモデルの中身は
common/database/model_mixins/product_mixins.py
common/database/model_mixins/order_mixins.py
に書く
これを使用して(継承させて)
apps/user-api/app/models/products.py
apps/user-api/app/models/orders
に定義を行う。


models/__init__.pyにも記載をお願いします

モデルの記載が終わったら、make resetコマンドを実行することでマイグレーションの作成とDB反映されます

あとDBの確認もして欲しいです
DBクライアントアプリで確認するといいと思います！
なにかインストールしてますかね？
ちなみに僕はmysqlworkbenchを使ってます

**Comment by campbel2525** [comment]
models/usersを参考にお願いします！

**Comment by nabecamel** [comment]
@campbel2525 
回答ありがとうございます！
DBのクライアントアプリは使ったことがないです！

**Comment by campbel2525** [comment]
mysqlworkbench
がおすすめなのでダウンロードお願いします！

https://www.mysql.com/jp/products/workbench/

**Comment by campbel2525** [comment]
@nabecamel 

もうしわけありません。
モデルの書く場所の指示間違えました。

具体的なモデルの中身は
common/database/model_mixins
にかいて
apps/user-api/app/models
には
common/database/model_mixins
で定義したものを使用する形になります


https://github.com/nabecamel/ec_demo/issues/5#issuecomment-2016331767
こちら修正しました

**Comment by nabecamel** [comment]
@campbel2525 
訂正ありがとうございます！
やってみます！

mysqlworkbenchはダウンロードしました！

**Comment by nabecamel** [comment]
@campbel2525 
foreign_keyについてどう取り扱うのが正しいのかで迷っております。
使いたいキーを指定しているファイルをimportして、新たに変数に格納する形でいいのでしょうか？

from user_mixins import UserMixin
                              ・
                              ・
                              ・
user_id = Column(BigInteger, ForeignKey('UserMixin.id'))
みたいな感じでいいんですかね？
もう一点質問なんですが、unsignedint型の定義は、Integer(Unsigned = True)でいいのでしょうか？

**Comment by campbel2525** [comment]
@nabecamel 
>user_id = Column(BigInteger, ForeignKey('UserMixin.id'))
みたいな感じでいいんですかね？

oders.pyを考えていますかね？

こんな感じにあると思います
order_mixins
```python
user_id = Column(BigInteger, ForeignKey("users.id"), nullable=False)
```

さらに1対多の関係の1の方、つまりユーザーの方に下記を入れてください
```python 
from sqlalchemy.orm import relationship
from sqlalchemy.orm import declared_attr

・
・
・
@declarative_mixin
class UserMixin:
・
・
・
    @declared_attr
    def orders(cls):
        return relationship("Order", backref="user")
```
この記述はマイグレーションとは関係がないのですが、モデル操作でかなり役に立ちます

user.odersでユーザーに紐づくodersが取得できたり
ordee.userでorderに紐づくユーザーが取得できます

先ほど追加したのでこちらを参考にしてみてください

https://github.com/campbel2525/fastapi-sample/tree/main/common/database/model_mixins


>もう一点質問なんですが、unsignedint型の定義は、Integer(Unsigned = True)でいいのでしょうか？

デフォルトでサポートしていないのでいったん、ただのint型でお願いします

**Comment by campbel2525** [comment]
あとモデルは
orders.py
products.py

のように複数系でお願いします

user.pyをusers.pyにするタスクも別途作りました
- https://github.com/nabecamel/ec_demo/issues/11

**Comment by nabecamel** [comment]
@campbel2525 
返信ありがとうございます！
foregin_keyは、orders.pyで書いて、orders_mixin.pyでは書かない感じですかね？
どこまでmixinに書いて、どこまでmodelsの方に書くのがいいのかがわからなくて。。。
修正の方もやっておきます！

**Comment by campbel2525** [comment]
@nabecamel 

申し訳ありません
上記のコメント間違えていました

フォーリンキーはmixinsに書きます
参考urlも間違えていたので修正しました

**Comment by nabecamel** [comment]
@campbel2525 
返信ありがとうございます！
承知しました！取り組んでみます！

**Comment by nabecamel** [comment]
@campbel2525 
参考urlを見させていただいて、疑問に思ったことがあったので質問させてください！
productテーブルについては、product_mixin.pyやproducts.pyなどは作らない感じでしょうか？
それとも、参考URLだから、全く同じ機能を持っているものではないため、上記のようなファイルがない感じでしょうか？

**Comment by nabecamel** [comment]
@campbel2525 
~~mysqlworkbenchを使って、データを確認しようと思っているのですが接続の方法があまり分かっていないので~~
~~教えてもらえると嬉しいです。~~
解決しました！
ただ、productsテーブルの内容が用事できてないです。。。
