### ISSUE TITLE
商品シーダーを作る

### ISSUE THREAD

**Issue by campbel2525** [nabecamel/ec_demo#8]
# タスクのゴール

商品シーダーを作り、`make reset`を実行するとDBにシードが入ること
レコードは20件ほど入れておけばOK

# 概要
シーダーとは、データベースにあらかじめ入れておくデータのことです

例えば、データベースをリセットするとデータが消えてしまいますが、シーダーを実行することで基礎データを入れることができるので便利です
商品データを入れておけば、商品一覧APIや商品取得APIを実行してもデータが取れるので開発がしやすくなります

# 処理内容
common/database/factories/user_factories.py
はユーザーデータのファトリーです

common/database/seeders/user_seeder.py
はユーザーデータのシードです

apps/user-api/app/console/commands/seeds.py
はシードの実行コマンドです

上記の使われ方は`user_factories.py`に1ユーザー分のデータを定義します
`user_seeder.py`で`user_factories.py`を呼び出してユーザーを複数作成するコードを書きます。
`seeds.py`では`user_seeder.py`を呼び出してユーザーを作成します

上記を参考にして
common/database/factories/product_factories.py
common/database/seeders/product_seeder.py
を作って
apps/user-api/app/console/commands/seeds.py
に指定する

タスクのゴールにも書いたが、`make reset`を実行してproductsテーブルにデータが入ればOK

**Comment by nabecamel** [comment]
@campbel2525 
コンフリクト解消しました！
失敗している気がするので、一応確認しただけたらと思います！

**Comment by campbel2525** [comment]
@nabecamel 

> 失敗している気がするので、一応確認しただけたらと思います！

こちらは懸念点がある場合はマージする前に確認した方が良かったですね
懸念点があるままマージするのは避けたいためです

mainブランチ確認しておきます！

**Comment by nabecamel** [comment]
@campbel2525 
なるほど、、、
お手数おかけしてすみません！！
